### ISSUE TITLE
Cite your references

### ISSUE THREAD

**Issue by Anis-Bensaid** [kapadias/mediumposts#1]
I am assuming you took the explanation for stemming and lemmatization from here and you didn't make any efforts to change some of the sentences. 
https://nlp.stanford.edu/IR-book/html/htmledition/stemming-and-lemmatization-1.html
Please reference your findings next time for intellectual integrity, especially if you are publishing these.

**Comment by kapadias** [comment]
@Anis-Bensaid  - thank you for bringing this to my attention, I have updated the Jupyter notebook with the list of references to have it consistent with the information shared on the medium post, link::https://towardsdatascience.com/building-blocks-text-pre-processing-641cae8ba3bf

The references were present on Medium Post all the way but now is also available in the code (Will soon update other notebooks as well)

Also, I share your concern around intellectual integrity, but, please note, the purpose of publishing this on Medium, and personal GitHub account is that the content is not meant to be original - and, I generally agree with your comments around adding references!

I am closing this for now - and once again, thank you for bringing it to my attention!
