### ISSUE TITLE
Introduction to Topic Modeling.ipynb not found

### ISSUE THREAD

**Issue by versant2612** [kapadias/mediumposts#10]
I am looking for the notebook about LDA with Scikit-learn

From https://www.mygreatlearning.com/blog/understanding-latent-dirichlet-allocation/

LDA in python:

There are few python packages which can be used for LDA based topic modeling. The popular packages are Genism and Scikit-learn. Amongst the two packages, Gensim is the top contender. ‘Topic Modeling with Gensim’  is a good reference to learn about using the Gensim package for performing LDA.  ‘Introduction to topic modeling’ serves as a good reference for using Scikit-learn package to perform LDA

**Comment by kapadias** [comment]
@versant2612 here's the link to the notebook, I suppose, you are looking for: https://github.com/kapadias/mediumposts/blob/master/natural_language_processing/topic_modeling/notebooks/Introduction%20to%20Topic%20Modeling.ipynb

**Comment by versant2612** [comment]
@kapadias thank you.
