### ISSUE TITLE
error at final code block >>> import pyLDAvis.gensim

### ISSUE THREAD

**Issue by protrolium** [kapadias/mediumposts#7]
I am receiving the following error regarding pyLDAvis and gensim
`ModuleNotFoundError: No module named 'pyLDAvis.gensim'`

Have not had any luck finding solution on Google, although it seems to have something to do with how updated version and name change. I tried `import pyLDAvis.gensim_models as gensimvis` which also did not work.

**Comment by protrolium** [comment]
I finally got this to work as intended by this document, but it necessitated downgrading to gensim 3.8.3, and then changing the first `import` as well as the attribute name to `pyLDAvis.gensim_models.prepare()`

```
import pyLDAvis.gensim_models
import pickle 
import pyLDAvis

# Visualize the topics
pyLDAvis.enable_notebook()

LDAvis_data_filepath = os.path.join('./results/'+str(num_topics))

# # this is a bit time consuming - make the if statement True
# # if you want to execute visualization prep yourself
if 1 == 1:
    LDAvis_prepared = pyLDAvis.gensim_models.prepare(lda_model, corpus, id2word)
    with open(LDAvis_data_filepath, 'wb') as f:
        pickle.dump(LDAvis_prepared, f)

# load the pre-prepared pyLDAvis data from disk
with open(LDAvis_data_filepath, 'rb') as f:
    LDAvis_prepared = pickle.load(f)

pyLDAvis.save_html(LDAvis_prepared, './results/ldavis_prepared_'+ str(num_topics) +'.html')

LDAvis_prepared
```

**Comment by kapadias** [comment]
Closing it since it is resolved!

**Comment by Summi07** [comment]
LDAvis_data_filepath = os.path.join('./results/'+str(num_topics))
......
with open(LDAvis_data_filepath, 'wb') as f:

error in this line
FileNotFoundError: [Errno 2] No such file or directory: './results/10'
